spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
#        - id: first-service
#          uri: lb://first-service
#          predicates:
#            - Method=GET
#        - id: second-service
#          uri: lb://second-service
#          predicates:
#            - Method=GET
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter
            preLogger: true
            postLogger: true

server:
  port: 8000