spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE # Eureka를 사용하는 경우
          predicates:
            - Path=/members/** # 모든 /members 경로를 포함
          filters:
          # 필터 설정이 필요하다면 여기에 추가
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter
            preLogger: true
            postLogger: true

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true # ??? ?? ????