spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE # Eureka를 사용하는 경우
          predicates: # Method predicate 까지 있었다면, "/members/** && (Method=GET 일 경우)GET" 이여야만 라우팅 해준다.
            - Path=/members/**, /points/** # 모든 /members 경로를 포함
          filters:
            - JwtFilter
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter
            preLogger: true
            postLogger: true

server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true # ??? ?? ????

jwt:
  secretKey : e9013edcc71fee14ac0b407e65e2f187b99e0365d9a31cf13ea2680b79e134718cd9777a7eea4b3a21aa16018e53a2c687843451a72c99ca3ffc05f4f0a21b4d