name: BackEnd - CI/CD
on:
  push:
    branches:
      - main

env:
#  DOCKER_REGISTRY:  ${{ secrets.DEVSEO_SERVER_PUBLIC_IP }}:5443
#  IMAGE_REPO: uahannam
  SERVICE_NAME: gateway-service

jobs:
#  build_and_push:
#    name: Build and analyze
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Set Yaml
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ./src/main/resources/bootstrap.yml
#        env:
#          spring.cloud.config.uri: http://${{ secrets.DEVSEO_SERVER_PUBLIC_IP }}:9999
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'corretto'
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v3
#        with:
#          cache-read-only: false
#          gradle-home-cache-includes: |
#            caches
#            notifications
#            jdks
#
#      - name: Gradlew grant
#        run: chmod +x ./gradlew
#
#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: clean bootJar
#
#      - name: Build and Push to Harbor
#        run: |
#          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.SERVICE_NAME }}:latest .

  run_docker_image:
#    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Auth to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SUNGMIN_SA_KEY }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: server
          project_id: ${{ secrets.GCP_SUNGMIN_PROJECT_ID }}

#      - name: Docker Stop Container
#        run: docker stop $(docker ps --format '{{.ID}} {{.Names}}' | awk '/${{ env.SERVICE_NAME }}/{print $1}') 2>/dev/null || true
#
#      - name: Docker Pull Image and Run New Container
#        run: docker run --name ${{ env.SERVICE_NAME }} --rm -d -p 8000:8000 ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.SERVICE_NAME }}:latest
#
#      - name: Delete Old Docker Image
#        run: docker images | grep '${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.SERVICE_NAME }}' | grep '<none>' |awk '{print $3}' | xargs -r docker rmi

#  notify_success:
#    needs: [ build_and_push, run_docker_image ]
#    runs-on: ubuntu-latest
#    if: success()
#    steps:
#      - uses: 8398a7/action-slack@v3
#        with:
#          status: success
#          author_name: CI Monitoring_bot
#          fields: repo,message,commit,eventName,ref,workflow,author,took
#          if_mention: always
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#
#  notify_failure:
#    needs: [ build_and_push, run_docker_image ]
#    runs-on: ubuntu-latest
#    if: failure()
#    steps:
#      - uses: 8398a7/action-slack@v3
#        with:
#          status: failure
#          author_name: CI Monitoring_bot
#          fields: repo,message,commit,eventName,ref,workflow,author,took
#          if_mention: always
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}